"""
STEP file name parser for GMSH/OCC import.

Parses STEP (ISO-10303-21) files to extract the mapping between
named PRODUCTs and the solid geometry volumes that OCC will import,
so that after import into GMSH the volumes can be associated back
to their original product names.

Handles two STEP structures:

1. **Simple multi-body parts** — solids live directly inside
   SHAPE_REPRESENTATION:
       PRODUCT -> ... -> SHAPE_DEFINITION_REPRESENTATION
         -> SHAPE_REPRESENTATION (items include MANIFOLD_SOLID_BREP)

2. **Assemblies** — solids live in a separate
   ADVANCED_BREP_SHAPE_REPRESENTATION linked via a
   SHAPE_REPRESENTATION_RELATIONSHIP, and instances are placed via
   NEXT_ASSEMBLY_USAGE_OCCURRENCE + REPRESENTATION_RELATIONSHIP
   (compound type with SHAPE_REPRESENTATION_RELATIONSHIP):
       PRODUCT -> ... -> SHAPE_DEFINITION_REPRESENTATION
         -> SHAPE_REPRESENTATION (items are only axes)
              |
              +-- SHAPE_REPRESENTATION_RELATIONSHIP
              |     -> ADVANCED_BREP_SHAPE_REPRESENTATION
              |          -> MANIFOLD_SOLID_BREP
              |
              +-- REPRESENTATION_RELATIONSHIP (compound, with transform)
                    -> links parent SR to child SR (assembly instances)

   Instance counts come from NEXT_ASSEMBLY_USAGE_OCCURRENCE.
   
   This was entirely generated by Claude Code.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class StepProduct:
    """A named product found in the STEP file."""
    name: str
    product_id: int                       # STEP entity id of PRODUCT
    product_definition_id: int | None = None
    shape_rep_id: int | None = None       # SHAPE_REPRESENTATION entity id
    solid_ids: list[int] = field(default_factory=list)  # MANIFOLD_SOLID_BREP ids
    num_solids_per_instance: int = 0


@dataclass
class StepAssemblyInstance:
    """One placed instance of a child product inside an assembly."""
    child_product_name: str
    child_pd_id: int                      # PRODUCT_DEFINITION of the child
    parent_pd_id: int                     # PRODUCT_DEFINITION of the parent
    nauo_id: int                          # NEXT_ASSEMBLY_USAGE_OCCURRENCE id


# ---------------------------------------------------------------------------
# Entity types that represent solid volumes
# ---------------------------------------------------------------------------

SOLID_TYPES = frozenset({
    'MANIFOLD_SOLID_BREP',
    'BREP_WITH_VOIDS',
    'FACETED_BREP',
})

# Entity types for shape representations that can hold solids
SHAPE_REP_TYPES = frozenset({
    'SHAPE_REPRESENTATION',
    'ADVANCED_BREP_SHAPE_REPRESENTATION',
})


# ---------------------------------------------------------------------------
# Low-level STEP parsing
# ---------------------------------------------------------------------------

def _parse_step_entities(text: str) -> dict[int, tuple[str, str]]:
    """Parse all STEP DATA entities into ``{id: (TYPE_NAME, raw_params)}``.

    Compound entities like ``( TYPE1() TYPE2() ... )`` get type '_COMPOUND'.
    The raw body string is also scanned for any embedded type keywords so
    that compound entities can be identified by the types they contain.
    """
    data_match = re.search(r'DATA\s*;(.*?)ENDSEC\s*;', text, re.DOTALL)
    if not data_match:
        raise ValueError("Could not find DATA section in STEP file")

    data_section = re.sub(r'\s+', ' ', data_match.group(1)).strip()

    entities: dict[int, tuple[str, str]] = {}
    for match in re.finditer(r'#(\d+)\s*=\s*([^;]+?)\s*;', data_section):
        eid = int(match.group(1))
        body = match.group(2).strip()

        if body.startswith('('):
            # Compound entity — extract all uppercase type names from the body
            # so we can later check membership (e.g. contains
            # 'REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION')
            entities[eid] = ('_COMPOUND', body)
        else:
            m = re.match(r"([A-Z_][A-Z0-9_]*)\s*\(\s*(.*)\s*\)", body, re.DOTALL)
            if m:
                entities[eid] = (m.group(1), m.group(2).strip())
            else:
                entities[eid] = ('_UNKNOWN', body)

    return entities


def _extract_refs(params: str) -> list[int]:
    """Return all ``#NNN`` references found anywhere in *params*."""
    return [int(m) for m in re.findall(r'#(\d+)', params)]


def _extract_strings(params: str) -> list[str]:
    """Return all single-quoted string values in *params*."""
    return re.findall(r"'([^']*)'", params)


def _extract_paren_list_refs(params: str) -> list[int]:
    """Return refs from the first ``(#a, #b, ...)`` group in *params*.

    Needed because SHAPE_REPRESENTATION stores its geometry items in an
    inner parenthesized list:  ``'name', (#11, #15, #165), #315``
    """
    depth = 0
    start = None
    for i, ch in enumerate(params):
        if ch == '(':
            if depth == 0:
                start = i
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0 and start is not None:
                inner = params[start + 1:i]
                refs = [int(m) for m in re.findall(r'#(\d+)', inner)]
                if refs:
                    return refs
                start = None
    return []


def _body_contains_type(body: str, typename: str) -> bool:
    """Check whether a compound entity body contains *typename* as a keyword."""
    return bool(re.search(r'\b' + re.escape(typename) + r'\b', body))


# ---------------------------------------------------------------------------
# High-level: build index tables from parsed entities
# ---------------------------------------------------------------------------

class _StepIndex:
    """Internal index over all parsed STEP entities.

    Builds reverse-lookup tables for the entity types we care about.
    """

    def __init__(self, entities: dict[int, tuple[str, str]]):
        self.entities = entities

        # type -> {eid: all refs in params}
        self.by_type: dict[str, dict[int, list[int]]] = {}
        # eid -> primary type string (or '_COMPOUND')
        self.etype: dict[int, str] = {}

        for eid, (et, params) in entities.items():
            self.etype[eid] = et
            refs = _extract_refs(params)
            self.by_type.setdefault(et, {})[eid] = refs

    # -- helpers -------------------------------------------------------------

    def refs_of(self, eid: int) -> list[int]:
        et = self.etype.get(eid)
        if et is None:
            return []
        return self.by_type.get(et, {}).get(eid, [])

    def params(self, eid: int) -> str:
        return self.entities[eid][1] if eid in self.entities else ''

    def find_referencing(self, target: int, etype: str) -> int | None:
        """Find the first entity of *etype* whose params reference *target*."""
        for eid, refs in self.by_type.get(etype, {}).items():
            if target in refs:
                return eid
        return None

    def find_all_referencing(self, target: int, etype: str) -> list[int]:
        """Find all entities of *etype* referencing *target*."""
        return [eid for eid, refs in self.by_type.get(etype, {}).items()
                if target in refs]

    def find_referencing_compound(self, target: int, containing: str) -> list[int]:
        """Find compound entities that reference *target* AND whose body
        contains the keyword *containing*."""
        results = []
        for eid, refs in self.by_type.get('_COMPOUND', {}).items():
            if target in refs:
                body = self.params(eid)
                if _body_contains_type(body, containing):
                    results.append(eid)
        return results

    # -- product chain -------------------------------------------------------

    def product_name(self, product_eid: int) -> str:
        strings = _extract_strings(self.params(product_eid))
        return strings[0] if strings else f'Product_{product_eid}'

    def product_to_pd(self, product_eid: int) -> int | None:
        """PRODUCT -> PRODUCT_DEFINITION (via PRODUCT_DEFINITION_FORMATION)."""
        # PDF can be PRODUCT_DEFINITION_FORMATION or
        # PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE
        pdf_eid = None
        for etype_key in ('PRODUCT_DEFINITION_FORMATION',
                          'PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE'):
            pdf_eid = self.find_referencing(product_eid, etype_key)
            if pdf_eid is not None:
                break
        if pdf_eid is None:
            return None
        return self.find_referencing(pdf_eid, 'PRODUCT_DEFINITION')

    def pd_to_sr(self, pd_eid: int) -> int | None:
        """PRODUCT_DEFINITION -> SHAPE_REPRESENTATION
        (via PDS -> SDR -> SR)."""
        pds_eid = self.find_referencing(pd_eid, 'PRODUCT_DEFINITION_SHAPE')
        if pds_eid is None:
            return None
        sdr_eid = self.find_referencing(pds_eid, 'SHAPE_DEFINITION_REPRESENTATION')
        if sdr_eid is None:
            return None
        for ref in self.refs_of(sdr_eid):
            if self.etype.get(ref) in SHAPE_REP_TYPES:
                return ref
        return None

    # -- solids from a shape representation ----------------------------------

    def sr_direct_solids(self, sr_eid: int) -> list[int]:
        """Return MANIFOLD_SOLID_BREP (etc.) ids listed directly in a
        SHAPE_REPRESENTATION's item list."""
        items = _extract_paren_list_refs(self.params(sr_eid))
        return [eid for eid in items if self.etype.get(eid) in SOLID_TYPES]

    def sr_linked_solids(self, sr_eid: int) -> list[int]:
        """Return solids reachable via SHAPE_REPRESENTATION_RELATIONSHIP
        from *sr_eid* to an ADVANCED_BREP_SHAPE_REPRESENTATION."""
        solids = []
        # SHAPE_REPRESENTATION_RELATIONSHIP is a normal (non-compound) entity
        # with params: ('name', 'desc', #sr1, #sr2)
        for srr_eid in self.find_all_referencing(sr_eid,
                                                  'SHAPE_REPRESENTATION_RELATIONSHIP'):
            refs = self.refs_of(srr_eid)
            for ref in refs:
                if ref == sr_eid:
                    continue
                if self.etype.get(ref) in SHAPE_REP_TYPES:
                    solids.extend(self.sr_direct_solids(ref))
        return solids

    def sr_all_solids(self, sr_eid: int) -> list[int]:
        """All solids for a SHAPE_REPRESENTATION — direct + linked."""
        return self.sr_direct_solids(sr_eid) + self.sr_linked_solids(sr_eid)

    # -- assembly instances --------------------------------------------------

    def assembly_instances(self) -> list[tuple[int, int, int]]:
        """Return list of (nauo_eid, parent_pd_eid, child_pd_eid) from all
        NEXT_ASSEMBLY_USAGE_OCCURRENCE entities."""
        results = []
        for eid in self.by_type.get('NEXT_ASSEMBLY_USAGE_OCCURRENCE', {}):
            refs = self.refs_of(eid)
            # NAUO params: ('id', 'name', 'desc', #parent_PD, #child_PD, $)
            pds = [r for r in refs
                   if self.etype.get(r) == 'PRODUCT_DEFINITION']
            if len(pds) >= 2:
                results.append((eid, pds[0], pds[1]))
            elif len(pds) == 1:
                # Sometimes both refs point to PD — deduplicate
                # In practice the first PD ref is parent, second is child
                # but if they collapsed, we can't distinguish
                results.append((eid, pds[0], pds[0]))
        return results

    def count_assembly_child_instances(self, parent_pd: int) -> dict[int, int]:
        """For a given parent PRODUCT_DEFINITION, count how many times each
        child PRODUCT_DEFINITION appears as an assembly instance."""
        counts: dict[int, int] = {}
        for _, p_pd, c_pd in self.assembly_instances():
            if p_pd == parent_pd:
                counts[c_pd] = counts.get(c_pd, 0) + 1
        return counts

    def pd_to_product_eid(self, pd_eid: int) -> int | None:
        """PRODUCT_DEFINITION -> PRODUCT (reverse of product_to_pd)."""
        refs = self.refs_of(pd_eid)
        for ref in refs:
            etype = self.etype.get(ref)
            if etype in ('PRODUCT_DEFINITION_FORMATION',
                         'PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE'):
                pdf_refs = self.refs_of(ref)
                for pr in pdf_refs:
                    if self.etype.get(pr) == 'PRODUCT':
                        return pr
        return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def parse_step_names(filepath: str | Path) -> dict[str, list[int]]:
    """Parse a STEP file and return ``{product_name: [volume_indices]}``.

    Volume indices are 0-based and ordered to match the expected
    GMSH/OCC import order (by entity-id order within the STEP file).

    Handles both simple multi-body part files and assembly files with
    NEXT_ASSEMBLY_USAGE_OCCURRENCE instances.

    Args:
        filepath: Path to the ``.step`` / ``.stp`` file.

    Returns:
        Dictionary mapping product name strings to lists of 0-based
        volume indices.  The union of all lists covers
        ``range(total_volumes)``.
    """
    filepath = Path(filepath)
    text = filepath.read_text(encoding='utf-8', errors='replace')
    entities = _parse_step_entities(text)
    idx = _StepIndex(entities)

    # Collect all products
    products: dict[int, str] = {}  # product_eid -> name
    for eid in idx.by_type.get('PRODUCT', {}):
        products[eid] = idx.product_name(eid)

    # Build product_eid -> product_definition_eid mapping
    prod_to_pd: dict[int, int] = {}
    for prod_eid in products:
        pd = idx.product_to_pd(prod_eid)
        if pd is not None:
            prod_to_pd[prod_eid] = pd

    # Build product_definition -> product_eid reverse mapping
    pd_to_prod: dict[int, int] = {v: k for k, v in prod_to_pd.items()}

    # For each product, find its SHAPE_REPRESENTATION and count its solids
    prod_sr: dict[int, int | None] = {}       # product_eid -> sr_eid
    prod_solids: dict[int, list[int]] = {}     # product_eid -> [solid_eids]
    for prod_eid, pd_eid in prod_to_pd.items():
        sr = idx.pd_to_sr(pd_eid)
        prod_sr[prod_eid] = sr
        if sr is not None:
            prod_solids[prod_eid] = idx.sr_all_solids(sr)
        else:
            prod_solids[prod_eid] = []

    # Check for assembly structure via NEXT_ASSEMBLY_USAGE_OCCURRENCE
    all_nauo = idx.assembly_instances()
    is_assembly = len(all_nauo) > 0

    if is_assembly:
        return _resolve_assembly(idx, products, prod_to_pd, pd_to_prod,
                                 prod_solids, all_nauo)
    else:
        return _resolve_simple(idx, products, prod_to_pd, prod_solids)


def _resolve_simple(
    idx: _StepIndex,
    products: dict[int, str],
    prod_to_pd: dict[int, int],
    prod_solids: dict[int, list[int]],
) -> dict[str, list[int]]:
    """Resolve volume names for a simple (non-assembly) STEP file.

    Each product may own one or more MANIFOLD_SOLID_BREPs.
    We order volumes by the solid entity id within the file.
    """
    # Build flat list: (solid_eid, product_name)
    entries: list[tuple[int, str]] = []
    for prod_eid in sorted(products.keys()):
        name = products[prod_eid]
        for solid_eid in sorted(prod_solids.get(prod_eid, [])):
            entries.append((solid_eid, name))

    # Sort by solid entity id (approximates STEP file order = OCC import order)
    entries.sort(key=lambda x: x[0])

    mapping: dict[str, list[int]] = {}
    for vol_idx, (_, name) in enumerate(entries):
        mapping.setdefault(name, []).append(vol_idx)
    return mapping


def _resolve_assembly(
    idx: _StepIndex,
    products: dict[int, str],
    prod_to_pd: dict[int, int],
    pd_to_prod: dict[int, int],
    prod_solids: dict[int, list[int]],
    all_nauo: list[tuple[int, int, int]],
) -> dict[str, list[int]]:
    """Resolve volume names for an assembly STEP file.

    Each NEXT_ASSEMBLY_USAGE_OCCURRENCE is one placed instance of a child
    product.  The child product owns N solids, so each NAUO contributes
    N volumes.  We order instances by NAUO entity id.
    """
    # Sort NAUO by entity id to approximate file/import order
    sorted_nauo = sorted(all_nauo, key=lambda x: x[0])

    # Build flat volume list
    mapping: dict[str, list[int]] = {}
    vol_idx = 0

    for nauo_eid, parent_pd, child_pd in sorted_nauo:
        child_prod = pd_to_prod.get(child_pd)
        if child_prod is None:
            # Try harder: reverse-trace from PD to PRODUCT
            child_prod = idx.pd_to_product_eid(child_pd)

        if child_prod is not None:
            child_name = products.get(child_prod, f'Unknown_{child_pd}')
            n_solids = len(prod_solids.get(child_prod, []))
        else:
            child_name = f'Unknown_{child_pd}'
            n_solids = 0

        # If we couldn't find any solids via the chain, assume 1
        # (OCC will still import *something* for each NAUO)
        if n_solids == 0:
            n_solids = 1

        for _ in range(n_solids):
            mapping.setdefault(child_name, []).append(vol_idx)
            vol_idx += 1

    return mapping


def get_volume_names(filepath: str | Path) -> list[str]:
    """Return a flat list of product names, one per volume, in import order.

    If a product appears multiple times (assembly instances or multiple
    solids), its name is repeated.

    Example::

        ['Housing', '039_POGO', '039_POGO', ..., '039_POGO']

    Args:
        filepath: Path to the STEP file.

    Returns:
        List of name strings, length equals the expected number of
        GMSH/OCC volumes.
    """
    mapping = parse_step_names(filepath)
    # Flatten back into ordered list
    total = sum(len(v) for v in mapping.values())
    names: list[str | None] = [None] * total
    for name, indices in mapping.items():
        for i in indices:
            names[i] = name
    # Fill any gaps (shouldn't happen, but be safe)
    return [n if n is not None else f'Unknown_{i}' for i, n in enumerate(names)]